[CAPITAL]
user_id = A126347885
password = GC3CR0SK6CA4

[DATABASE]
host = localhost
user = stocks
password = jbR3nKAMheB9aKE1
database = stocks_ml
charset = utf8mb4
local_infile = True
# default command timeout (例如: connect_timeout) 並非 pymysql 的直接參數，若有需要請參考 pymysql 相關文件設定。
