[CAPITAL]
user_id = A126347885
password = GC3CR0SK6CA4

[DATABASE]
host = localhost
user = stocks
password = jbR3nKAMheB9aKE1
database = stocks_ml
charset = utf8mb4
local_infile = True

[discord]
# 請在此填入您的 Webhook URL
webhook_url = https://discordapp.com/api/webhooks/1352581561169481799/hmrb_Eeaka_TAuB78Mu7tuyCAOiUHff3eD_7yJygD_srkHOK7HzlOkWmjLNoeVSLRHGb